language: android
android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - platform-tools
    - extra-android-support 
    - extra-android-m2repository
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace
