language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:

  components:
  
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21

script: ./gradlew connectedAndroidTest
