language: android
android:
  components:
    - tools
    - tools 
    - platform-tools
    - build-tools-26.1.1
    - android-26
before_install:
  - yes | sdkmanager "platforms;android-27"
script:
   - ./gradlew build connectedCheck
