language: android
jdk:
  - oraclejdk8
components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
  - ./gradlew test build
